sources:
  # - name: DeepL
  #   handler:
  #     newOpenapi:
  #       fallbackFormat:  json
  #       oasFilePath: ./deepl.oas.json
    # - name: DeepL sanitized
    # handler:
    #   newOpenapi:
    #     oasFilePath: ./deepl.sanitized.yml
  
  # - name: DeepL
  #   handler:
  #     newOpenapi:
  #       oasFilePath: https://raw.githubusercontent.com/DeepLcom/openapi/main/openapi.json 
  - name: DeepL old
    handler:
      openapi:
        operationHeaders:
          Authorization: DeepL-Auth-Key d5bede0e-5731-01cc-b2d2-dbb2094a9a17:fx
        includeHttpDetails: true
        provideErrorExtensions: true
        source: ./deepl.oas.json
  # - name: Jira sanitized
  #   handler:
  #     newOpenapi:
  #       oasFilePath: ./jira.sanitized.yml
  # - name: Jira new
  #   handler:
  #     newOpenapi:
  #       oasFilePath: https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json
  # - name: Jira old
  #   handler:
  #     openapi:
  #       source: https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

